### ISSUE TITLE
A case between url.parse() and readFile()

### ISSUE THREAD

**Issue by xiaozhaolnsy** [xiaozhaolnsy/node-study-note#2]
path : study-code/step17_server.js
source :
...
http.createServer(function(req,res){
    var urlinfo = url.parse(req.url);
    var pathname = urlinfo.pathname;
    fs.readFile(pathname.substr(1),function(err,data){
...

trace :
_http_outgoing.js:510
    throw new ERR_INVALID_HTTP_TOKEN('Header name', name);
    ^
TypeError [ERR_INVALID_HTTP_TOKEN]: Header name must be a valid HTTP token ["Content Type"]    at processHeader (_http_outgoing.js:457:5)
    at ServerResponse._storeHeader (_http_outgoing.js:371:11)
    at ServerResponse.writeHead (_http_server.js:312:8)
    at ReadFileContext.callback (E:\SpringCloud\node-study-note\study-code\step17_server.js:21:17)
    at FSReqCallback.readFileAfterOpen [as oncomplete] (fs.js:256:13) {
  code: 'ERR_INVALID_HTTP_TOKEN'
}

**Comment by xiaozhaolnsy** [comment]
1. "Content Type is not right." leads to the trace.
if(err){
            res.writeHead(404,{'**_Content Type_**':'text/html'});
}

--> Change to Content-Type.(must contains a '-' ,- - - - - -).

2.Page Not Founded would lead to a 404 in console.
Just as well,it won't show to users.

--> **Optionally** adding validations.
